# Generated by Django 5.1.5 on 2025-01-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Natural', 'Физическое лицо'), ('Legal', 'Юридическое лицо')], max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
